//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retail_HD.Setting {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class SQL : global::System.Configuration.ApplicationSettingsBase {
        
        private static SQL defaultInstance = ((SQL)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SQL())));
        
        public static SQL Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rochdclogp01")]
        public string _ServerName {
            get {
                return ((string)(this["_ServerName"]));
            }
            set {
                this["_ServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RetailHD")]
        public string _Database {
            get {
                return ((string)(this["_Database"]));
            }
            set {
                this["_Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select
	[Calls].[id] as [ID],
	[Calls].[store] as [Store],
	[Calls].[date] [Date],
	[Technicians].[initials] as [Tech],
	[Categories].[category] as [Category],
	[Topics].[topic] as [Topic],
	[Calls].[details] as [Details],
	[Calls].[type] as [In/Out],
	[Calls].[trax] as [Trax],
	[Calls].[url] as [URL]
from
	[Calls]
	left join
		[Topics] on [Calls].[topID] = [Topics].id
	left join
		[Categories] on [Topics].[catID] = [Categories].[id]
	left join
		[Technicians] on [Calls].[techID] = [Technicians].[id]
where
	[Calls].[store] = @store
order by
	[Calls].[date] desc

")]
        public string _RecentCallsByStore {
            get {
                return ((string)(this["_RecentCallsByStore"]));
            }
            set {
                this["_RecentCallsByStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT \r\n\t[computer] \r\nFROM \r\n\t[Computers] \r\nWHERE \r\n\t[store] = @store")]
        public string _ComputersByStore {
            get {
                return ((string)(this["_ComputersByStore"]));
            }
            set {
                this["_ComputersByStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select \r\n\t[category], \r\n\t[topic], \r\n\t[mandatory] \r\nfrom \r\n\t[Topics] \r\n\tleft join " +
            "\r\n\t\t[Categories] \r\n\ton \r\n\t\t[Topics].[catID] = [Categories].[id]\r\nwhere\r\n\t[active" +
            "] = \'TRUE\'")]
        public string _CategoriesWithTopics {
            get {
                return ((string)(this["_CategoriesWithTopics"]));
            }
            set {
                this["_CategoriesWithTopics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"insert into 
	[Calls] (
		[store], 
		[details], 
		[catID], 
		[topID], 
		[type], 
		[techID],
		[trax],
		[url]) 
values (
	@store, 
	@details, 
	(Select [id] from [Categories] where [category] = @category), 
	(select [id] from [Topics] where [topic] = @topic ), 
	@type, 
	(select [id] from [Technicians] where [technician] = @technician),
	@trax,
	@url
	)
")]
        public string _InsertCall {
            get {
                return ((string)(this["_InsertCall"]));
            }
            set {
                this["_InsertCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select\r\n\tcount([techID]) [Total]\r\nfrom\r\n\t[Calls]\r\n\tleft join \r\n\t\t[Technicians]\r\n\t" +
            "on\r\n\t\t[Calls].[techID] = [Technicians].[id]\r\nwhere\r\n\t[date] > dbo.StartOfDay() a" +
            "nd\r\n\tlower([Technicians].[technician]) = lower(@TECH) and\r\n\tlower([type]) = \'in\'" +
            "\r\n")]
        public string _CallCount_User {
            get {
                return ((string)(this["_CallCount_User"]));
            }
            set {
                this["_CallCount_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"update
	[Calls] 
set 
	[store] = @store, 
	[catID] = (select [catID] from [Topics] where topic = @topic), 
	[topID] = (select [id] from [Topics] where [topic] = @topic), 
	[details] = @details, 
	[type] = @type, 
	[trax] = @trax,
	[url] = @url
where 
	[Calls].[id] = @id
")]
        public string _UpdateCall {
            get {
                return ((string)(this["_UpdateCall"]));
            }
            set {
                this["_UpdateCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Insert into [Topics] ([topic], [catID], [active], [mandatory])\r\nvalues\r\n\t(@topic," +
            "\r\n\t(select [Categories].[id] from [Categories] where [category] = @category),\r\n\t" +
            "\'true\',\r\n\t@mandatory)\r\n")]
        public string _InsertTopic {
            get {
                return ((string)(this["_InsertTopic"]));
            }
            set {
                this["_InsertTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT \r\n\t[store]\r\nFROM \r\n\t[Phones]\r\nWHERE \r\n\t[phone] LIKE \'%\' + @phone + \'%\'\r\n")]
        public string _StoreByPhone {
            get {
                return ((string)(this["_StoreByPhone"]));
            }
            set {
                this["_StoreByPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select\r\n\tcount([techID]) [Total]\r\nfrom\r\n\t[Calls]\r\n\tleft join \r\n\t\t[Technicians]\r\n\t" +
            "on\r\n\t\t[Calls].[techID] = [Technicians].[id]\r\nwhere\r\n\t[date] > dbo.StartOfDay() a" +
            "nd\r\n\tlower([type]) = \'in\'")]
        public string _CallCount_Team {
            get {
                return ((string)(this["_CallCount_Team"]));
            }
            set {
                this["_CallCount_Team"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DECLARE @STORE INT\r\nDECLARE @TYPE VARCHAR(50)\r\nDECLARE @DATE1 DATE\r\nDECLARE @DATE" +
            "2 DATE\r\nDECLARE @CATEGORY VARCHAR(50)\r\nDECLARE @TOPIC VARCHAR(50)\r\nDECLARE @TECH" +
            " VARCHAR(50)\r\nDECLARE @DETAILS VARCHAR(2000)\r\nDECLARE @TRAX BIT\r\nDECLARE @URL VA" +
            "RCHAR(2000)\r\n")]
        public string _HistoryDeclare {
            get {
                return ((string)(this["_HistoryDeclare"]));
            }
            set {
                this["_HistoryDeclare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT
	TOP {0}
	[Calls].[id] as [ID],
	[Calls].[date] as [Date],
	[Calls].[store] as [Store],
	[Technicians].[initials] as [Tech],
	[Categories].[category] as [Category],
	[Topics].[topic] as [Topic],
	[Calls].[details] as [Details],
	[Calls].[type] as [In/Out],
	[Calls].[trax] as [Trax],
	[Calls].[url] as [URL]
FROM
	[Calls]
	INNER JOIN
		[Technicians]
	ON
		[Calls].[techID] = [Technicians].[id]
	INNER JOIN
		[Topics]
	ON
		[Calls].[topID] = [Topics].[id]
	INNER JOIN
		[Categories]
	ON
		[Topics].[catID] = [Categories].[id]
WHERE
	(@STORE IS NULL OR ([store] = @STORE)) AND
	(@TYPE IS NULL OR ([type] = @TYPE)) AND
	(@DATE1 IS NULL OR (CONVERT(DATE,[date]) LIKE @DATE1)) AND
	(@CATEGORY IS NULL OR ([category] = @CATEGORY)) AND
	(@TOPIC IS NULL OR ([topic] = @TOPIC)) AND
	(@TECH IS NULL OR ([initials] = @TECH)) AND
	(@DETAILS IS NULL OR (LOWER([details]) LIKE '%'+LOWER(@DETAILS)+'%')) AND
	(@TRAX IS NULL OR ([trax] = @TRAX)) AND
	(@URL IS NULL OR ([url] = @URL))
ORDER BY
	[date]
DESC 
")]
        public string _HistorySearch {
            get {
                return ((string)(this["_HistorySearch"]));
            }
            set {
                this["_HistorySearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT
	[Calls].[id] as [ID],
	[Calls].[date] as [Date],
	[Calls].[store] as [Store],
	[Technicians].[initials] as [Tech],
	[Categories].[category] as [Category],
	[Topics].[topic] as [Topic],
	[Calls].[details] as [Details],
	[Calls].[type] as [In/Out],
	[Calls].[trax] as [Trax],
	[Calls].[url] as [URL]
FROM
	[Calls]
	INNER JOIN
		[Technicians]
	ON
		[Calls].[techID] = [Technicians].[id]
	INNER JOIN
		[Topics]
	ON
		[Calls].[topID] = [Topics].[id]
	INNER JOIN
		[Categories]
	ON
		[Topics].[catID] = [Categories].[id]
WHERE
	(@STORE IS NULL OR ([store] = @STORE)) AND
	(@TYPE IS NULL OR ([type] = @TYPE)) AND
	(@DATE1 IS NULL OR (CONVERT(DATE,[date]) BETWEEN @DATE1 AND @DATE2)) AND
	(@CATEGORY IS NULL OR ([category] = @CATEGORY)) AND
	(@TOPIC IS NULL OR ([topic] = @TOPIC)) AND
	(@TECH IS NULL OR ([initials] = @TECH)) AND
	(@DETAILS IS NULL OR (LOWER([details]) LIKE '%'+LOWER(@DETAILS)+'%')) AND
	(@TRAX IS NULL OR ([trax] = @TRAX)) AND
	(@URL IS NULL OR ([url] = @URL))
ORDER BY
	[date]
DESC 
")]
        public string _HistorySearchRange {
            get {
                return ((string)(this["_HistorySearchRange"]));
            }
            set {
                this["_HistorySearchRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT TOP 1
	[address],
	[city],
	[dm],
	[email],
	[manager],
	[MP],
	[name],
	[P].phone,
	[state],
	[type],
	[TZ],
	[zip],
	[pos],
	[pos_gate],
	[sensor],
	[sensor_gate],
	[mim],
	[mim_gate],
	[income],
	[rank],
	[BAMS],
	[SVS],
	[TID1],
	[TID2],
	[TID3],
	[TID4]

FROM
	[Stores] as S
	inner join 
		[Phones] as P
	on [S].[store] = [P].[store]
WHERE
	[S].[store] = @store
ORDER BY
	[P].[line]
")]
        public string _StoreInfo {
            get {
                return ((string)(this["_StoreInfo"]));
            }
            set {
                this["_StoreInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT
	TOP 1
	[Categories].[category]
FROM
	[Calls]
	INNER JOIN
		[Categories]
	ON
		[Calls].[catID] = [Categories].[id]
	INNER JOIN
		[Technicians]
	ON
		[Calls].[techID] = [Technicians].[id]
WHERE
	[Technicians].[technician] = @TECH
ORDER BY
	[Calls].[id]
DESC
")]
        public string _LastCategory {
            get {
                return ((string)(this["_LastCategory"]));
            }
            set {
                this["_LastCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DECLARE @TZ VARCHAR(50)
DECLARE @MP VARCHAR(50)
DECLARE @DM VARCHAR(50)
DECLARE @NAME VARCHAR(50)
DECLARE @TYPE VARCHAR(50)
DECLARE @ADDRESS VARCHAR(50)
DECLARE @CITY VARCHAR(50)
DECLARE @STATE VARCHAR(50)
DECLARE @ZIP VARCHAR(50)
DECLARE @PHONE VARCHAR(50)
")]
        public string _StoreSearchDeclare {
            get {
                return ((string)(this["_StoreSearchDeclare"]));
            }
            set {
                this["_StoreSearchDeclare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT
	[store],
	[TZ],
	[dm],
	[name],
	[type],
	[address],
	[city],
	[state],
	[zip],
	[phone],
	[rank],
	[income]
FROM
	[Stores]
WHERE
	(@TZ IS NULL OR (LOWER([TZ]) = LOWER(@TZ))) AND
	(@MP IS NULL OR ([MP] = @MP)) AND
	(@DM IS NULL OR (LOWER([dm]) LIKE '%'+LOWER(@DM)+'%')) AND
	(@NAME IS NULL OR (LOWER([name]) LIKE '%'+LOWER(@NAME)+'%')) AND
	(@TYPE IS NULL OR (LOWER([type]) LIKE '%'+LOWER(@TYPE)+'%')) AND
	(@ADDRESS IS NULL OR (LOWER([address]) LIKE '%'+LOWER(@ADDRESS)+'%')) AND
	(@CITY IS NULL OR (LOWER([city]) LIKE '%'+LOWER(@CITY)+'%')) AND
	(@STATE IS NULL OR (LOWER([state]) = LOWER(@STATE))) AND
	(@ZIP IS NULL OR (LOWER([zip]) = LOWER(@ZIP))) AND
	(@PHONE IS NULL OR ([phone] = dbo.RemoveNonNumericCharacters
(@PHONE)))
")]
        public string _StoreSearch {
            get {
                return ((string)(this["_StoreSearch"]));
            }
            set {
                this["_StoreSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"INSERT INTO 
	[STORES] (
		[store],
		[TZ],
		[MP],
		[manager],
		[dm],
		[mall],
		[name],
		[type],
		[address],
		[city],
		[state],
		[zip],
		[email],
		[pos_gate],
		[pos],
		[mim_gate],
		[mim],
		[sensor_gate],
		[sensor]
) 
VALUES (
	dbo.InitCap(@store),
	UPPER(@TZ),
	dbo.InitCap(@MP),
	dbo.InitCap(@manager),
	dbo.InitCap(@dm),
	dbo.InitCap(@mall),
	dbo.InitCap(@name),
	dbo.InitCap(@type),
	dbo.InitCap(@address),
	dbo.InitCap(@city),
	UPPER(@state),
	@zip,
	@email,
	@pos_gate,
	@pos,
	@mim_gate,
	@mim,
	@sensor_gate,
	@sensor
)

INSERT INTO
	[Phones] (
		[phone],
		[store]
)
VALUES (
	dbo.RemoveNonNumericCharacters(@phone),
	@store
)

")]
        public string _InsertStore {
            get {
                return ((string)(this["_InsertStore"]));
            }
            set {
                this["_InsertStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"UPDATE 
	[Stores]
SET 
	[manager] = @manager,
	[MP] = @mpid,
	[address] = @address,
	[email] = @email,
	[pos] = @pos,
	[city] = @city,
	[dm] = @dm,
	[name] = @name,
	[type] = @type,
	[state] = @state,
	[zip] = @zip,
	[TZ] = @tz
WHERE 
	[store] = @store

UPDATE
	[Phones]
SET
	[phone] = dbo.RemoveNonNumericCharacters(@phone)
")]
        public string _UpdateStore {
            get {
                return ((string)(this["_UpdateStore"]));
            }
            set {
                this["_UpdateStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO [Info] ([tab], [order]) VALUES (@tab, @order)")]
        public string _InsertInfoTab {
            get {
                return ((string)(this["_InsertInfoTab"]));
            }
            set {
                this["_InsertInfoTab"] = value;
            }
        }
    }
}
