//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap agents {
            get {
                object obj = ResourceManager.GetObject("agents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;!-- These arguments are read by vfQueryUpdate on application startup --&gt;
        ///  &lt;tblArgs&gt;
        ///    &lt;Argument&gt;commtype&lt;/Argument&gt;
        ///    &lt;Description&gt;RS232 (default), USB, or TCPIP&lt;/Description&gt;
        ///    &lt;Value&gt;USB&lt;/Value&gt;
        ///  &lt;/tblArgs&gt;
        ///  &lt;tblArgs&gt;
        ///    &lt;Argument&gt;cp&lt;/Argument&gt;
        ///    &lt;Description&gt;Comm Port Number - If you leave it empty for USB, it will look in registry for COM port&lt;/Description&gt;
        ///    &lt;Value&gt;9&lt;/Value&gt;
        ///  &lt;/tblArgs&gt;
        ///  &lt;tblArgs&gt;
        ///    &lt;Argument&gt;ip [rest of string was truncated]&quot;;.
        /// </summary>
        public static string argsXML {
            get {
                return ResourceManager.GetString("argsXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///REM
        ///:importCertRoot
        ///	verify &gt;nul
        ///	certutil.exe -store authroot | findstr &quot;040000000001154b5ac394&quot;
        ///	IF &apos;%ERRORLEVEL%&apos;==&apos;0&apos; goto importCertRoot2
        ///	verify &gt;nul
        ///	certutil -addstore -f &quot;authroot&quot; &quot;C:\Temp\global.cer&quot;
        ///
        ///:importCertRoot2
        ///	verify &gt;nul
        ///	certutil -store authroot | findstr &quot;9b7e0649a33e62b9d5ee90487129ef57&quot;
        ///	IF &apos;%ERRORLEVEL%&apos;==&apos;0&apos; goto exit
        ///	verify &gt;nul
        ///	certutil -addstore -f &quot;authroot&quot; &quot;C:\Temp\verisign-root.cer&quot;
        ///
        ///:exit
        ///ping -n 5 &gt;nul
        ///.
        /// </summary>
        public static string batCerts {
            get {
                return ResourceManager.GetString("batCerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SET LANG=ENU
        ///@SET FILE_SERVER=ROCSEP01
        ///@ECHO OFF
        ///
        ///
        ///:sep1214x32
        ///echo 32bit Windows installing version 1214x32
        ///start &quot;\\%FILE_SERVER%\sep12installs\My Company_Rockford_RetailStores_Upgrades_WIN32BIT\Symantec Endpoint Protection version 12.1.4013.4013 - English\Sep.msi&quot; &quot;\\%FILE_SERVER%\sep12installs\My Company_Rockford_RetailStores_Upgrades_WIN32BIT\Symantec Endpoint Protection version 12.1.4013.4013 - English\Sep.msi&quot; /QB
        ///
        ///exit.
        /// </summary>
        public static string batInstallEndpoint12 {
            get {
                return ResourceManager.GetString("batInstallEndpoint12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///
        ///	SET A=%1
        ///	SET S=%2
        ///	ECHO %S% %A%
        ///	
        ///:BEGIN
        ///	IF %S%==credit  CALL:CREDIT
        ///	IF %S%==sql CALL:SQL
        ///	IF %S%==pca CALL:PCA
        ///	IF %S%==citrix CALL:CITRIX
        ///	IF %S%==verifone CALL:VERIFONE
        ///	IF %S%==transnet CALL:TRANSNET
        ///	IF %S%==dameware CALL:DAMEWARE
        ///	CALL:WAIT
        ///GOTO:DONE
        ///
        ///:CREDIT
        ///	IF %A%==start CALL:creditSTART
        ///	IF %A%==stop CALL:creditSTOP
        ///	IF %a%==restart (
        ///		CALL:creditSTOP
        ///		CALL:WAIT
        ///		CALL:creditSTART
        ///	)
        ///GOTO:EOF
        ///	
        ///:creditSTART
        ///	NET START &quot;RIBROKER&quot;
        ///	NET START &quot;CDCA MULTI  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string batServices {
            get {
                return ResourceManager.GetString("batServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///
        ///:: ===================================
        ///::      UNLOCK POWERUSER ACCOUNTS
        ///:: ===================================
        ///
        ///:VARIABLES
        ///	SET EMPNUM=%1
        ///	SET RAWDATE=%DATE:~-10%
        ///	SET YYYY=%RAWDATE:~-4%
        ///	SET MM=%RAWDATE:~0,2%
        ///	SET DAYMON=%RAWDATE:~-7%
        ///	SET DD=%DAYMON:~0,2%
        ///	SET DSPACE=0
        ///	IF &quot;%DAYMON:~0,1%&quot;==&quot; &quot; SET DD=%DSPACE%%DAYMON:~1,1%
        ///	SET RAWTIME=%TIME:~0,5%
        ///	SET HH=%RAWTIME:~0,2%
        ///	SET HSPACE=0
        ///	IF &quot;%RAWTIME:~0,1%&quot;==&quot; &quot; SET HH=%HSPACE%%RAWTIME:~1,1%
        ///	SET MN=%RAWTIME:~3%
        ///	SET MSPACE=0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string batUnlock {
            get {
                return ResourceManager.GetString("batUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///
        ///net localgroup administrators wwwint\wsadmin /delete
        ///
        ///net localgroup administrators wwwint\wsadminsretail /add
        ///
        ///ping -n 6 127.0.0.1 &gt; NUL.
        /// </summary>
        public static string batWSAdmin {
            get {
                return ResourceManager.GetString("batWSAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BOS {
            get {
                object obj = ResourceManager.GetObject("BOS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Contra_33 {
            get {
                object obj = ResourceManager.GetObject("Contra_33", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ferp {
            get {
                object obj = ResourceManager.GetObject("ferp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Finger {
            get {
                object obj = ResourceManager.GetObject("Finger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap glen_tassi {
            get {
                object obj = ResourceManager.GetObject("glen_tassi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap helpdesk_fire {
            get {
                object obj = ResourceManager.GetObject("helpdesk_fire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icoMain {
            get {
                object obj = ResourceManager.GetObject("icoMain", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_browser {
            get {
                object obj = ResourceManager.GetObject("icon_browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_folder {
            get {
                object obj = ResourceManager.GetObject("icon_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_in {
            get {
                object obj = ResourceManager.GetObject("icon_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_key {
            get {
                object obj = ResourceManager.GetObject("icon_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_key_2 {
            get {
                object obj = ResourceManager.GetObject("icon_key_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_keys {
            get {
                object obj = ResourceManager.GetObject("icon_keys", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_list {
            get {
                object obj = ResourceManager.GetObject("icon_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_marquee {
            get {
                object obj = ResourceManager.GetObject("icon_marquee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_marquee_download {
            get {
                object obj = ResourceManager.GetObject("icon_marquee_download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_marquee_minus {
            get {
                object obj = ResourceManager.GetObject("icon_marquee_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_marquee_plus {
            get {
                object obj = ResourceManager.GetObject("icon_marquee_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_marquee_upload {
            get {
                object obj = ResourceManager.GetObject("icon_marquee_upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_maximise {
            get {
                object obj = ResourceManager.GetObject("icon_maximise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_menu {
            get {
                object obj = ResourceManager.GetObject("icon_menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_menu_2 {
            get {
                object obj = ResourceManager.GetObject("icon_menu_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_menu_pull_down {
            get {
                object obj = ResourceManager.GetObject("icon_menu_pull_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_menu_pull_up {
            get {
                object obj = ResourceManager.GetObject("icon_menu_pull_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_minus {
            get {
                object obj = ResourceManager.GetObject("icon_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_mixer {
            get {
                object obj = ResourceManager.GetObject("icon_mixer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_nope {
            get {
                object obj = ResourceManager.GetObject("icon_nope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_paper_ripped {
            get {
                object obj = ResourceManager.GetObject("icon_paper_ripped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_paper_roll {
            get {
                object obj = ResourceManager.GetObject("icon_paper_roll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_paper_roll_ripped {
            get {
                object obj = ResourceManager.GetObject("icon_paper_roll_ripped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_paragraph_center {
            get {
                object obj = ResourceManager.GetObject("icon_paragraph_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_paragraph_center_2 {
            get {
                object obj = ResourceManager.GetObject("icon_paragraph_center_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_paragraph_justify {
            get {
                object obj = ResourceManager.GetObject("icon_paragraph_justify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_paragraph_justify_2 {
            get {
                object obj = ResourceManager.GetObject("icon_paragraph_justify_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_paragraph_left {
            get {
                object obj = ResourceManager.GetObject("icon_paragraph_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_paragraph_left_2 {
            get {
                object obj = ResourceManager.GetObject("icon_paragraph_left_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_paragraph_right {
            get {
                object obj = ResourceManager.GetObject("icon_paragraph_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_paragraph_right_2 {
            get {
                object obj = ResourceManager.GetObject("icon_paragraph_right_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_phone1 {
            get {
                object obj = ResourceManager.GetObject("icon_phone1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_play {
            get {
                object obj = ResourceManager.GetObject("icon_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_plus {
            get {
                object obj = ResourceManager.GetObject("icon_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_power {
            get {
                object obj = ResourceManager.GetObject("icon_power", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_pull {
            get {
                object obj = ResourceManager.GetObject("icon_pull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_repeat {
            get {
                object obj = ResourceManager.GetObject("icon_repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_repeat_2 {
            get {
                object obj = ResourceManager.GetObject("icon_repeat_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_rulers {
            get {
                object obj = ResourceManager.GetObject("icon_rulers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_settings {
            get {
                object obj = ResourceManager.GetObject("icon_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_settings_2 {
            get {
                object obj = ResourceManager.GetObject("icon_settings_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_settings_3 {
            get {
                object obj = ResourceManager.GetObject("icon_settings_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_settings_4 {
            get {
                object obj = ResourceManager.GetObject("icon_settings_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_shred {
            get {
                object obj = ResourceManager.GetObject("icon_shred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_shuffle {
            get {
                object obj = ResourceManager.GetObject("icon_shuffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_sleep {
            get {
                object obj = ResourceManager.GetObject("icon_sleep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_spam {
            get {
                object obj = ResourceManager.GetObject("icon_spam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_spam_2 {
            get {
                object obj = ResourceManager.GetObject("icon_spam_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_speech_bubble_center {
            get {
                object obj = ResourceManager.GetObject("icon_speech_bubble_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_spinner_3 {
            get {
                object obj = ResourceManager.GetObject("icon_spinner_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_split {
            get {
                object obj = ResourceManager.GetObject("icon_split", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_split_2 {
            get {
                object obj = ResourceManager.GetObject("icon_split_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_stop {
            get {
                object obj = ResourceManager.GetObject("icon_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_subtract {
            get {
                object obj = ResourceManager.GetObject("icon_subtract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_support {
            get {
                object obj = ResourceManager.GetObject("icon_support", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_support_2 {
            get {
                object obj = ResourceManager.GetObject("icon_support_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_support_3 {
            get {
                object obj = ResourceManager.GetObject("icon_support_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_swap {
            get {
                object obj = ResourceManager.GetObject("icon_swap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_swap_2 {
            get {
                object obj = ResourceManager.GetObject("icon_swap_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_switch_off {
            get {
                object obj = ResourceManager.GetObject("icon_switch_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_switch_on {
            get {
                object obj = ResourceManager.GetObject("icon_switch_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_terminal {
            get {
                object obj = ResourceManager.GetObject("icon_terminal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_terminal_2 {
            get {
                object obj = ResourceManager.GetObject("icon_terminal_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_terminal_3 {
            get {
                object obj = ResourceManager.GetObject("icon_terminal_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_timeline {
            get {
                object obj = ResourceManager.GetObject("icon_timeline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_toggle_off {
            get {
                object obj = ResourceManager.GetObject("icon_toggle_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_toggle_on {
            get {
                object obj = ResourceManager.GetObject("icon_toggle_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_transfer {
            get {
                object obj = ResourceManager.GetObject("icon_transfer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_unlocked {
            get {
                object obj = ResourceManager.GetObject("icon_unlocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_video {
            get {
                object obj = ResourceManager.GetObject("icon_video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_video_2 {
            get {
                object obj = ResourceManager.GetObject("icon_video_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_watch {
            get {
                object obj = ResourceManager.GetObject("icon_watch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_watch_2 {
            get {
                object obj = ResourceManager.GetObject("icon_watch_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_windows {
            get {
                object obj = ResourceManager.GetObject("icon_windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap magnifying {
            get {
                object obj = ResourceManager.GetObject("magnifying", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mobile_phone {
            get {
                object obj = ResourceManager.GetObject("mobile_phone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Scott_Purpose {
            get {
                object obj = ResourceManager.GetObject("Scott_Purpose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings_icon {
            get {
                object obj = ResourceManager.GetObject("settings_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sundial {
            get {
                object obj = ResourceManager.GetObject("sundial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wat_help {
            get {
                object obj = ResourceManager.GetObject("wat_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///
        ///DEL C:\Temp\7zDUMP\*.* /Q
        ///
        ///
        ///SET RAWDATE=%DATE:~-10%
        ///SET MM=%RAWDATE:~0,2%
        ///SET DAYMON=%RAWDATE:~-7%
        ///SET DD=%DAYMON:~0,2%
        ///SET YYYY=%RAWDATE:~-4%
        ///
        ///SET POSPATH=%C:\Program Files\SAP\Retail Systems\Point of Sale%
        ///SET RIBPATH=%C:\Program Files\RedIron Technologies\RedIron Broker%
        ///SET MCMPATH=%C:\MerchantConnectMulti%
        ///SET MX9PATH=%C:\Program Files\VeriFone\MX915\UpdateFiles%
        ///MKDIR C:\Temp\7zDUMP
        ///SET TMPPATH=C:\Temp\7zDUMP\
        ///
        ///:ZIPMCM
        ///C:\
        ///CD \TEMP
        ///CD 7zDUMP
        ///
        ///
        ///IF EXIST %TMPPATH%MCMLO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Zip_Logs {
            get {
                return ResourceManager.GetString("Zip_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function create-7zip([String] $aDirectory, [String] $aZipfile){
        ///    [string]$pathToZipExe = &quot;C:\Temp\7za.exe&quot;;
        ///    [Array]$arguments = &quot;a&quot;, &quot;-tzip&quot;, &quot;$aZipfile&quot;, &quot;$aDirectory&quot;;
        ///    &amp; $pathToZipExe $arguments;
        ///}
        ///
        ///
        ///$Computer = Get-WmiObject -Class Win32_ComputerSystem
        ///$Nameage = &quot;CreditLogs&quot;
        ///
        ///create-7zip &quot;C:\Temp\7zDump\*.*&quot;  &quot;C:\Temp\7zDump\$env:computername-$Nameage.7z&quot;.
        /// </summary>
        public static string Zipper {
            get {
                return ResourceManager.GetString("Zipper", resourceCulture);
            }
        }
    }
}
