//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wwwint\\roc\\IS-Share\\Helpdesk\\Retail Helpdesk")]
        public string _NetworkShare {
            get {
                return ((string)(this["_NetworkShare"]));
            }
            set {
                this["_NetworkShare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wwwint\\roc\\techtmp\\bergman\\Toolsmenu.bat")]
        public string _OldMenuPath {
            get {
                return ((string)(this["_OldMenuPath"]));
            }
            set {
                this["_OldMenuPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _SettingsUpgradeCompleted {
            get {
                return ((bool)(this["_SettingsUpgradeCompleted"]));
            }
            set {
                this["_SettingsUpgradeCompleted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _PeoplesoftUpgrade {
            get {
                return ((bool)(this["_PeoplesoftUpgrade"]));
            }
            set {
                this["_PeoplesoftUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _PeoplesoftPopupThreadRunning {
            get {
                return ((bool)(this["_PeoplesoftPopupThreadRunning"]));
            }
            set {
                this["_PeoplesoftPopupThreadRunning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _PeoplesoftUsername {
            get {
                return ((string)(this["_PeoplesoftUsername"]));
            }
            set {
                this["_PeoplesoftUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _PeoplesoftPassword {
            get {
                return ((string)(this["_PeoplesoftPassword"]));
            }
            set {
                this["_PeoplesoftPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _ApplicationRetail {
            get {
                return ((bool)(this["_ApplicationRetail"]));
            }
            set {
                this["_ApplicationRetail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-03-01")]
        public global::System.DateTime _MostRecentLogSent {
            get {
                return ((global::System.DateTime)(this["_MostRecentLogSent"]));
            }
            set {
                this["_MostRecentLogSent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("unlock.bat")]
        public string _BatUnlock {
            get {
                return ((string)(this["_BatUnlock"]));
            }
            set {
                this["_BatUnlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("services.bat")]
        public string _BatServices {
            get {
                return ((string)(this["_BatServices"]));
            }
            set {
                this["_BatServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\VeriFone\\MX915\\vfQueryUpdate\\args.xml")]
        public string _ArgsXMLpath {
            get {
                return ((string)(this["_ArgsXMLpath"]));
            }
            set {
                this["_ArgsXMLpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
        public string _TempPath {
            get {
                return ((string)(this["_TempPath"]));
            }
            set {
                this["_TempPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InstallEndpoint12.bat")]
        public string _BatEndpoint {
            get {
                return ((string)(this["_BatEndpoint"]));
            }
            set {
                this["_BatEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ziplogs.bat")]
        public string _BatZip {
            get {
                return ((string)(this["_BatZip"]));
            }
            set {
                this["_BatZip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zipper.ps1")]
        public string _PSZip {
            get {
                return ((string)(this["_PSZip"]));
            }
            set {
                this["_PSZip"] = value;
            }
        }
    }
}
