//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wwwint\\roc\\IS-Share\\Helpdesk\\Retail Helpdesk")]
        public string _NetworkShare {
            get {
                return ((string)(this["_NetworkShare"]));
            }
            set {
                this["_NetworkShare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\wwwint\\roc\\techtmp\\bergman\\Toolsmenu.bat")]
        public string _OldMenuPath {
            get {
                return ((string)(this["_OldMenuPath"]));
            }
            set {
                this["_OldMenuPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("unlock.bat")]
        public string _BatUnlock {
            get {
                return ((string)(this["_BatUnlock"]));
            }
            set {
                this["_BatUnlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("services.bat")]
        public string _BatServices {
            get {
                return ((string)(this["_BatServices"]));
            }
            set {
                this["_BatServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\VeriFone\\MX915\\vfQueryUpdate\\args.xml")]
        public string _ArgsXMLpath {
            get {
                return ((string)(this["_ArgsXMLpath"]));
            }
            set {
                this["_ArgsXMLpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\")]
        public string _TempPath {
            get {
                return ((string)(this["_TempPath"]));
            }
            set {
                this["_TempPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InstallEndpoint12.bat")]
        public string _BatEndpoint {
            get {
                return ((string)(this["_BatEndpoint"]));
            }
            set {
                this["_BatEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ziplogs.bat")]
        public string _BatZip {
            get {
                return ((string)(this["_BatZip"]));
            }
            set {
                this["_BatZip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zipper.ps1")]
        public string _PSZip {
            get {
                return ((string)(this["_PSZip"]));
            }
            set {
                this["_PSZip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wsadmin.bat")]
        public string _WSAdmin {
            get {
                return ((string)(this["_WSAdmin"]));
            }
            set {
                this["_WSAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>4.2.12.178</string>\r\n  <string>4.2.12.161</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection _multiVersions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["_multiVersions"]));
            }
            set {
                this["_multiVersions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>2.0.0.926</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection _redIronVersions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["_redIronVersions"]));
            }
            set {
                this["_redIronVersions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>4.4.5-20151127</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection _vfVersions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["_vfVersions"]));
            }
            set {
                this["_vfVersions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Build1149</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection _POSBuildVersion {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["_POSBuildVersion"]));
            }
            set {
                this["_POSBuildVersion"] = value;
            }
        }
    }
}
