//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class SQLSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SQLSettings defaultInstance = ((SQLSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SQLSettings())));
        
        public static SQLSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rochdclogp01")]
        public string _ServerName {
            get {
                return ((string)(this["_ServerName"]));
            }
            set {
                this["_ServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RetailHD")]
        public string _Database {
            get {
                return ((string)(this["_Database"]));
            }
            set {
                this["_Database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select
	[Calls].[id] as [ID],
	[Calls].[store] as [Store],
	[Calls].[date] [Date],
	[Technicians].[initials] as [Tech],
	[Categories].[category] as [Category],
	[Topics].[topic] as [Topic],
	[Calls].[details] as [Details],
	[Calls].[type] as [In/Out],
	[Calls].[trax] as [Trax],
	[Calls].[url] as [URL]
from
	[Calls]
	left join
		[Topics] on [Calls].[topID] = [Topics].id
	left join
		[Categories] on [Topics].[catID] = [Categories].[id]
	left join
		[Technicians] on [Calls].[techID] = [Technicians].[id]
where
	[Calls].[store] = @store
order by
	[Calls].[date] desc

")]
        public string _RecentCallsByStore {
            get {
                return ((string)(this["_RecentCallsByStore"]));
            }
            set {
                this["_RecentCallsByStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT \n\t[computer] \nFROM \n\t[Computers] \nWHERE \n\t[store] = @store")]
        public string _ComputersByStore {
            get {
                return ((string)(this["_ComputersByStore"]));
            }
            set {
                this["_ComputersByStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select \n\t[category], \n\t[topic], \n\t[mandatory] \nfrom \n\t[Topics] \n\tleft join \n\t\t[Ca" +
            "tegories] \n\ton \n\t\t[Topics].[catID] = [Categories].[id]\nwhere\n\t[active] = \'TRUE\'")]
        public string _CategoriesWithTopics {
            get {
                return ((string)(this["_CategoriesWithTopics"]));
            }
            set {
                this["_CategoriesWithTopics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"insert into 
	[Calls] (
		[store], 
		[details], 
		[catID], 
		[topID], 
		[type], 
		[techID],
		[trax],
		[url]) 
values (
	@store, 
	@details, 
	(Select [id] from [Categories] where [category] = @category), 
	(select [id] from [Topics] where [topic] = @topic ), 
	@type, 
	(select [id] from [Technicians] where [technician] = @technician),
	@trax,
	@url
	)
")]
        public string _LogCall {
            get {
                return ((string)(this["_LogCall"]));
            }
            set {
                this["_LogCall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select\n\tcount([techID]) [Total]\nfrom\n\t[Calls]\n\tleft join \n\t\t[Technicians]\n\ton\n\t\t[" +
            "Calls].[techID] = [Technicians].[id]\nwhere\n\t[date] > dbo.StartOfDay() and\n\tlower" +
            "([Technicians].[technician]) = lower(@TECH) and\n\tlower([type]) = \'in\'\n")]
        public string _UserCallCount {
            get {
                return ((string)(this["_UserCallCount"]));
            }
            set {
                this["_UserCallCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"update
	[Calls] 
set 
	[store] = @store, 
	[catID] = (select [catID] from [Topics] where topic = @topic), 
	[topID] = (select [id] from [Topics] where [topic] = @topic), 
	[details] = @details, 
	[type] = @type, 
	[trax] = @trax,
	[url] = @url
where 
	[Calls].[id] = @id
")]
        public string _UpdateWrapUp {
            get {
                return ((string)(this["_UpdateWrapUp"]));
            }
            set {
                this["_UpdateWrapUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Insert into [Topics] ([topic], [catID], [active], [mandatory])\nvalues\n\t(@topic,\n\t" +
            "(select [Categories].[id] from [Categories] where [category] = @category),\n\t\'tru" +
            "e\',\n\t@mandatory)\n")]
        public string _AddCallTopic {
            get {
                return ((string)(this["_AddCallTopic"]));
            }
            set {
                this["_AddCallTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\nSELECT \r\n\t[store]\r\nFROM \r\n\t[Stores]\r\nWHERE \r\n\t[phone] LIKE @phone")]
        public string _StoreByPhone {
            get {
                return ((string)(this["_StoreByPhone"]));
            }
            set {
                this["_StoreByPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select\n\tcount([techID]) [Total]\nfrom\n\t[Calls]\n\tleft join \n\t\t[Technicians]\n\ton\n\t\t[" +
            "Calls].[techID] = [Technicians].[id]\nwhere\n\t[date] > dbo.StartOfDay() and\n\tlower" +
            "([type]) = \'in\'")]
        public string _TeamCallCount {
            get {
                return ((string)(this["_TeamCallCount"]));
            }
            set {
                this["_TeamCallCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DECLARE @STORE INT\nDECLARE @TYPE VARCHAR(50)\nDECLARE @DATE1 DATE\nDECLARE @DATE2 D" +
            "ATE\nDECLARE @CATEGORY VARCHAR(50)\nDECLARE @TOPIC VARCHAR(50)\nDECLARE @TECH VARCH" +
            "AR(50)\nDECLARE @DETAILS VARCHAR(2000)\nDECLARE @TRAX BIT\nDECLARE @URL VARCHAR(200" +
            "0)\n")]
        public string _HistoryDeclare {
            get {
                return ((string)(this["_HistoryDeclare"]));
            }
            set {
                this["_HistoryDeclare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT
	TOP {0}
	[Calls].[id] as [ID],
	[Calls].[date] as [Date],
	[Calls].[store] as [Store],
	[Technicians].[initials] as [Tech],
	[Categories].[category] as [Category],
	[Topics].[topic] as [Topic],
	[Calls].[details] as [Details],
	[Calls].[type] as [In/Out],
	[Calls].[trax] as [Trax],
	[Calls].[url] as [URL]
FROM
	[Calls]
	INNER JOIN
		[Technicians]
	ON
		[Calls].[techID] = [Technicians].[id]
	INNER JOIN
		[Topics]
	ON
		[Calls].[topID] = [Topics].[id]
	INNER JOIN
		[Categories]
	ON
		[Topics].[catID] = [Categories].[id]
WHERE
	(@STORE IS NULL OR ([store] = @STORE)) AND
	(@TYPE IS NULL OR ([type] = @TYPE)) AND
	(@DATE1 IS NULL OR (CONVERT(DATE,[date]) LIKE @DATE1)) AND
	(@CATEGORY IS NULL OR ([category] = @CATEGORY)) AND
	(@TOPIC IS NULL OR ([topic] = @TOPIC)) AND
	(@TECH IS NULL OR ([initials] = @TECH)) AND
	(@DETAILS IS NULL OR ([details] LIKE '%'+@DETAILS+'%')) AND
	(@TRAX IS NULL OR ([trax] = @TRAX)) AND
	(@URL IS NULL OR ([url] = @URL))
ORDER BY
	[date]
DESC 
")]
        public string _HistorySearch {
            get {
                return ((string)(this["_HistorySearch"]));
            }
            set {
                this["_HistorySearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT
	[Calls].[id] as [ID],
	[Calls].[date] as [Date],
	[Calls].[store] as [Store],
	[Technicians].[initials] as [Tech],
	[Categories].[category] as [Category],
	[Topics].[topic] as [Topic],
	[Calls].[details] as [Details],
	[Calls].[type] as [In/Out],
	[Calls].[trax] as [Trax],
	[Calls].[url] as [URL]
FROM
	[Calls]
	INNER JOIN
		[Technicians]
	ON
		[Calls].[techID] = [Technicians].[id]
	INNER JOIN
		[Topics]
	ON
		[Calls].[topID] = [Topics].[id]
	INNER JOIN
		[Categories]
	ON
		[Topics].[catID] = [Categories].[id]
WHERE
	(@STORE IS NULL OR ([store] = @STORE)) AND
	(@TYPE IS NULL OR ([type] = @TYPE)) AND
	(@DATE1 IS NULL OR (CONVERT(DATE,[date]) BETWEEN @DATE1 AND @DATE2)) AND
	(@CATEGORY IS NULL OR ([category] = @CATEGORY)) AND
	(@TOPIC IS NULL OR ([topic] = @TOPIC)) AND
	(@TECH IS NULL OR ([initials] = @TECH)) AND
	(@DETAILS IS NULL OR ([details] LIKE '%'+@DETAILS+'%')) AND
	(@TRAX IS NULL OR ([trax] = @TRAX)) AND
	(@URL IS NULL OR ([url] = @URL))
ORDER BY
	[date]
DESC 
")]
        public string _HistorySearchRange {
            get {
                return ((string)(this["_HistorySearchRange"]));
            }
            set {
                this["_HistorySearchRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT TOP 1
	[address],
	[city],
	[dm],
	[email],
	[manager],
	[MP],
	[name],
	[P].phone,
	[state],
	[type],
	[TZ],
	[zip],
	[pos],
	[pos_gate],
	[sensor],
	[sensor_gate],
	[mim],
	[mim_gate],
	[income],
	[rank],
	[BAMS],
	[SVS],
	[TID1],
	[TID2],
	[TID3],
	[TID4]

FROM
	[Stores] as S
	inner join 
		[Phones] as P
	on [S].[store] = [P].[store]
WHERE
	[S].[store] = @store
ORDER BY
	[P].[line]")]
        public string _StoreInfo {
            get {
                return ((string)(this["_StoreInfo"]));
            }
            set {
                this["_StoreInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT
	TOP 1
	[Categories].[category]
FROM
	[Calls]
	INNER JOIN
		[Categories]
	ON
		[Calls].[catID] = [Categories].[id]
	INNER JOIN
		[Technicians]
	ON
		[Calls].[techID] = [Technicians].[id]
WHERE
	[Technicians].[technician] = @TECH
ORDER BY
	[Calls].[id]
DESC
")]
        public string _LastCategory {
            get {
                return ((string)(this["_LastCategory"]));
            }
            set {
                this["_LastCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GlobalHD")]
        public string _DatabaseGlobal {
            get {
                return ((string)(this["_DatabaseGlobal"]));
            }
            set {
                this["_DatabaseGlobal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DECLARE @TZ VARCHAR(50)
DECLARE @MP VARCHAR(50)
DECLARE @DM VARCHAR(50)
DECLARE @NAME VARCHAR(50)
DECLARE @TYPE VARCHAR(50)
DECLARE @ADDRESS VARCHAR(50)
DECLARE @CITY VARCHAR(50)
DECLARE @STATE VARCHAR(50)
DECLARE @ZIP VARCHAR(50)
DECLARE @PHONE VARCHAR(50)
")]
        public string _StoreSearchDeclare {
            get {
                return ((string)(this["_StoreSearchDeclare"]));
            }
            set {
                this["_StoreSearchDeclare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT
	[store],
	[TZ],
	[dm],
	[name],
	[type],
	[address],
	[city],
	[state],
	[zip],
	[phone],
	[rank],
	[income]
FROM
	[Stores]
WHERE
	(@TZ IS NULL OR (LOWER([TZ]) = LOWER(@TZ))) AND
	(@MP IS NULL OR ([MP] = @MP)) AND
	(@DM IS NULL OR (LOWER([dm]) LIKE '%'+LOWER(@DM)+'%')) AND
	(@NAME IS NULL OR (LOWER([name]) LIKE '%'+LOWER(@NAME)+'%')) AND
	(@TYPE IS NULL OR (LOWER([type]) LIKE '%'+LOWER(@TYPE)+'%')) AND
	(@ADDRESS IS NULL OR (LOWER([address]) LIKE '%'+LOWER(@ADDRESS)+'%')) AND
	(@CITY IS NULL OR (LOWER([city]) LIKE '%'+LOWER(@CITY)+'%')) AND
	(@STATE IS NULL OR (LOWER([state]) = LOWER(@STATE))) AND
	(@ZIP IS NULL OR (LOWER([zip]) = LOWER(@ZIP))) AND
	(@PHONE IS NULL OR ([phone] = dbo.RemoveNonNumericCharacters
(@PHONE)))")]
        public string _StoreSearch {
            get {
                return ((string)(this["_StoreSearch"]));
            }
            set {
                this["_StoreSearch"] = value;
            }
        }
    }
}
