//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B9Weekly.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n<!DOCTYPE html><html><head>\r\n<style>\r\ntable, th, td {\r\nborder: 1px solid black;" +
            "\r\nborder-collapse: collapse;\r\n}\r\nth, td {\r\npadding: 5px;\r\n}\r\n</style></head>")]
        public string header {
            get {
                return ((string)(this["header"]));
            }
            set {
                this["header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n</body></html>")]
        public string footer {
            get {
                return ((string)(this["footer"]));
            }
            set {
                this["footer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>chad.gould@wwwinc.com</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection to {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["to"]));
            }
            set {
                this["to"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<table style=\"width:50%\">\r\n<tr><th>[Host_Name]</th><th>[Host_Agent_Version]</th><" +
            "th>[Host_Group]</th><th>[Upgrade_Status]</th><th>[Upgrade_Error]</th><th>[Upgrad" +
            "e_Error_Count]</th><th>[Upgrade_Error_Time]</th><th>[Tamper_Protect]</th></tr>\r\n" +
            "{0}\r\n</table>")]
        public string table {
            get {
                return ((string)(this["table"]));
            }
            set {
                this["table"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<tr><td>{0}</td><td>{1}</td><td>{2}</td><td>{3}</td><td>{4}</td><td>{5}</td><td>{" +
            "6}</td><td>{7}</td></tr>")]
        public string row {
            get {
                return ((string)(this["row"]));
            }
            set {
                this["row"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
SELECT
      [Host_Name]
      ,[Host_Agent_Version]
      ,[Host_Group]
      ,[Upgrade_Status]
      ,[Upgrade_Error]
      ,[Upgrade_Error_Count]
      ,[Upgrade_Error_Time]
      ,[Tamper_Protect]
  FROM [das].[dbo].[HostsGUI]
  ORDER BY [Host_Name]
")]
        public string sql {
            get {
                return ((string)(this["sql"]));
            }
            set {
                this["sql"] = value;
            }
        }
    }
}
