//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Batch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Batch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HDSharedServices.Resources.Batch", typeof(Batch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///
        ///:: ===================================
        ///::      UNLOCK POWERUSER ACCOUNTS
        ///:: ===================================
        ///
        ///:VARIABLES
        ///	SET EMPNUM=%1
        ///	SET RAWDATE=%DATE:~-10%
        ///	SET YYYY=%RAWDATE:~-4%
        ///	SET MM=%RAWDATE:~0,2%
        ///	SET DAYMON=%RAWDATE:~-7%
        ///	SET DD=%DAYMON:~0,2%
        ///	SET DSPACE=0
        ///	IF &quot;%DAYMON:~0,1%&quot;==&quot; &quot; SET DD=%DSPACE%%DAYMON:~1,1%
        ///	SET RAWTIME=%TIME:~0,5%
        ///	SET HH=%RAWTIME:~0,2%
        ///	SET HSPACE=0
        ///	IF &quot;%RAWTIME:~0,1%&quot;==&quot; &quot; SET HH=%HSPACE%%RAWTIME:~1,1%
        ///	SET MN=%RAWTIME:~3%
        ///	SET MSPACE=0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cashier {
            get {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SET LANG=ENU
        ///@SET FILE_SERVER=ROCSEP01
        ///@ECHO OFF
        ///
        ///
        ///:sep1214x32
        ///echo 32bit Windows installing version 1214x32
        ///start &quot;\\%FILE_SERVER%\sep12installs\My Company_Rockford_RetailStores_Upgrades_WIN32BIT\Symantec Endpoint Protection version 12.1.4013.4013 - English\Sep.msi&quot; &quot;\\%FILE_SERVER%\sep12installs\My Company_Rockford_RetailStores_Upgrades_WIN32BIT\Symantec Endpoint Protection version 12.1.4013.4013 - English\Sep.msi&quot; /QB
        ///
        ///exit.
        /// </summary>
        internal static string InstallEndpoint12 {
            get {
                return ResourceManager.GetString("InstallEndpoint12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///
        ///	SET A=%1
        ///	SET S=%2
        ///
        ///:BEGIN
        ///	IF %A%==start CALL:START 		
        ///	IF %A%==stop CALL:STOP
        ///	IF %A%==restart (
        ///		CALL:STOP
        ///		CALL:START
        ///	)
        ///GOTO:DONE
        ///
        ///:STOP
        ///	IF %S%==credit  CALL:cSTOP 
        ///	IF %S%==sql  CALL:sSTOP
        ///	IF %S%==pca CALL:pSTOP 
        ///	IF %S%==all ( 
        ///		CALL:cSTOP
        ///		CALL:sSTOP
        ///		CALL:pSTOP
        ///	)
        ///GOTO:EOF
        ///		
        ///:START
        ///	IF %S%==credit  CALL:cSTART 
        ///	IF %S%==sql  CALL:sSTART 
        ///	IF %S%==pca CALL:pSTART
        ///	IF %S%==all ( 
        ///		CALL:cSTART
        ///		CALL:sSTART
        ///		CALL:pSTART
        ///	)
        ///GOTO:EOF
        ///	
        ///:cSTART
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///
        ///ECHO %1
        ///
        ///PING 127.0.0.1
        ///PAUSE
        ///EXIT /B %ERRORLEVEL%
        ///.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
