//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailReport {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n<!DOCTYPE html><html><head>\r\n<style>\r\ntable, th, td {\r\nborder: 1px solid black;" +
            "\r\nborder-collapse: collapse;\r\n}\r\nth, td {\r\npadding: 5px;\r\n}\r\n</style></head>")]
        public string header {
            get {
                return ((string)(this["header"]));
            }
            set {
                this["header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</body></html>\r\n")]
        public string footer {
            get {
                return ((string)(this["footer"]));
            }
            set {
                this["footer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n<table style=\"width:50%\">\r\n<tr><th>Tech</th><th>Calls</th></tr>\r\n{0}\r\n</table>")]
        public string table_tech {
            get {
                return ((string)(this["table_tech"]));
            }
            set {
                this["table_tech"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<tr><td>{0}</td><td>{1}</td></tr>")]
        public string row_tech {
            get {
                return ((string)(this["row_tech"]));
            }
            set {
                this["row_tech"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n<table style=\"width:20%\">\r\n<tr><th>Total</th></tr>\r\n<tr><td>{0}</td></tr>\r\n</ta" +
            "ble>\r\n")]
        public string table_total {
            get {
                return ((string)(this["table_total"]));
            }
            set {
                this["table_total"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select\r\n\tt.full_name,\r\n\tcount(t.full_name) as [total]\r\nfrom\r\n\t[Calls] c\r\n\tinner j" +
            "oin\r\n\t\t[Technicians] t\r\n\ton\r\n\t\tc.techID = t.id\r\nwhere\r\n\tc.[date] > dbo.StartOfDa" +
            "y() - 1\r\n\tand dbo.StartOfDay() > c.date\r\ngroup by\r\n\tt.full_name\r\n")]
        public string select_techs_calls {
            get {
                return ((string)(this["select_techs_calls"]));
            }
            set {
                this["select_techs_calls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select\r\n\tcount(id) as [total]\r\nfrom\r\n\t[Calls] c\r\nwhere\r\n\tc.[date] > dbo.StartOfDa" +
            "y() - 1\r\n\tand dbo.StartOfDay() > c.date\r\n")]
        public string select_total_calls {
            get {
                return ((string)(this["select_total_calls"]));
            }
            set {
                this["select_total_calls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>gouldch@wwwinc.com</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection to {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["to"]));
            }
            set {
                this["to"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string from {
            get {
                return ((string)(this["from"]));
            }
            set {
                this["from"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yesterday\'s calls")]
        public string subject {
            get {
                return ((string)(this["subject"]));
            }
            set {
                this["subject"] = value;
            }
        }
    }
}
