//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelayedStartServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DelayedStartServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///
        ///	SET A=%1
        ///	SET S=%2
        ///
        ///:BEGIN
        ///	IF %A%==start CALL:START 		
        ///	IF %A%==stop CALL:STOP
        ///	IF %A%==restart (
        ///		CALL:STOP
        ///		CALL:START
        ///	)
        ///GOTO:DONE
        ///
        ///:STOP
        ///	IF %S%==credit  CALL:cSTOP 
        ///	IF %S%==sql  CALL:sSTOP 
        ///	IF %S%==all ( 
        ///		CALL:cSTOP
        ///		CALL:sSTOP
        ///	)
        ///GOTO:EOF
        ///		
        ///:START
        ///	IF %S%==credit  CALL:cSTART 
        ///	IF %S%==sql  CALL:sSTART 
        ///	IF %S%==all ( 
        ///		CALL:cSTART
        ///		CALL:sSTART
        ///	)
        ///GOTO:EOF
        ///	
        ///:cSTART
        ///	NET START &quot;RIBROKER&quot;
        ///	NET START &quot;CDCA MULTI CLIENT&quot;
        ///	NET START &quot;NFM CLIENT SER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string batServices {
            get {
                return ResourceManager.GetString("batServices", resourceCulture);
            }
        }
    }
}
