//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BananaHammock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BananaHammock.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///:importCertRoot
        ///	verify &gt;nul
        ///	echo finding cert 1
        ///	certutil.exe -store authroot | findstr &quot;040000000001154b5ac394&quot;
        ///	IF &apos;%ERRORLEVEL%&apos;==&apos;0&apos; goto importCertRoot2
        ///	verify &gt;nul
        ///	certutil -addstore -f &quot;authroot&quot; &quot;C:\Temp\global.cer&quot;
        ///
        ///:importCertRoot2
        ///	verify &gt;nul
        ///	echo finding cert 2
        ///	certutil -store authroot | findstr &quot;9b7e0649a33e62b9d5ee90487129ef57&quot;
        ///	IF &apos;%ERRORLEVEL%&apos;==&apos;0&apos; goto bit9
        ///	verify &gt;nul
        ///	certutil -addstore -f &quot;authroot&quot; &quot;C:\Temp\verisign-root.cer&quot;
        ///
        ///:bit9
        ///	cd C:\Program Fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string batCerts {
            get {
                return ResourceManager.GetString("batCerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///
        ///cd C:\Program Files\Bit9\Parity Agent
        ///dascli password 2H8-EVrv_,HXSTnV+UAyfg(B
        ///dascli healthcheck.
        /// </summary>
        internal static string batDascli {
            get {
                return ResourceManager.GetString("batDascli", resourceCulture);
            }
        }
    }
}
