//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit9Report {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n<!DOCTYPE html><html><head>\r\n<style>\r\ntable, th, td {\r\nborder: 1px solid black;" +
            "\r\nborder-collapse: collapse;\r\n}\r\nth, td {\r\npadding: 5px;\r\n}\r\n</style></head>")]
        public string header {
            get {
                return ((string)(this["header"]));
            }
            set {
                this["header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n<table style=\"width:50%\">\r\n<tr><th>Computer</th><th>Time</th><th>Subtype</th><t" +
            "h>Description</th><th>IP_Address</th></tr>\r\n{0}\r\n</table>")]
        public string ahcTable {
            get {
                return ((string)(this["ahcTable"]));
            }
            set {
                this["ahcTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<tr><td>{0}</td><td>{1}</td><td>{2}</td><td>{3}</td><td>{4}</td></tr>")]
        public string ahcRow {
            get {
                return ((string)(this["ahcRow"]));
            }
            set {
                this["ahcRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select
comp.Computer,
Timestamp,
Subtype,
Description,
events.IP_Address
from
das.bit9_public.ExEvents as [events]
inner join
	das.bit9_public.ExComputers as [comp] on
              [events].Computer_Id = [comp].Computer_Id
where
Subtype like '%health%' and
Description like '%failed%' and
[Timestamp] > dateadd( day, -1, getutcdate() )")]
        public string ahcSelect {
            get {
                return ((string)(this["ahcSelect"]));
            }
            set {
                this["ahcSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<table style=\"width:50%\">\r\n<tr><th>Computer</th><th>File_Name</th><th>Path_Name</" +
            "th><th>Time</th><th>User_Name</th><th>Process</th></tr>\r\n{0}\r\n</table>")]
        public string ebTable {
            get {
                return ((string)(this["ebTable"]));
            }
            set {
                this["ebTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<tr><td>{0}</td><td>{1}</td><td>{2}</td><td>{3}</td><td>{4}</td><td>{5}</td></tr>" +
            "")]
        public string ebRow {
            get {
                return ((string)(this["ebRow"]));
            }
            set {
                this["ebRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select 
comp.Computer,
File_Name,
Path_Name,
Timestamp,
User_Name,
process
from
das.bit9_public.ExEvents as [events]
inner join
       das.bit9_public.ExComputers as [comp] on
              [events].Computer_Id = [comp].Computer_Id
where
Subtype like '%block%' and 
[Timestamp] > dateadd( day, -1, getutcdate() )
")]
        public string ebSelect {
            get {
                return ((string)(this["ebSelect"]));
            }
            set {
                this["ebSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</body></html>\r\n")]
        public string footer {
            get {
                return ((string)(this["footer"]));
            }
            set {
                this["footer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>chad.gould@wwwinc.com</string>
  <string>jason.bergman@wwwinc.com</string>
  <string>michael.nedd@wwwinc.com</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection to {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["to"]));
            }
            set {
                this["to"] = value;
            }
        }
    }
}
